language: node_js
node_js:
  - "0.10"
  - "0.12"
before_install:
  - npm install -g gulp
  - npm install -g typescript
  - tsc
install: npm install
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - 'uwdub:Ry6mwlUX1aZevqiqmYLiA3N1'
    on_success: never
    on_failure: change
