name: Auto-merge Dependabot PRs
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  auto_merge:
    name: Auto-merge Dependabot PRs

    runs-on: ubuntu-latest

    steps:
      - uses: domoritz/dependabot-cron-action@296bc82715f7e25e12a1f51b66b8f43a6b1d79f1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-merge: 'minor'
          merge-method: 'rebase'
